// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: msgs.proto

package msgs

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//消息类型
type MsgType int32

const (
	MsgType_NULL_MSG_TYPE MsgType = 0
	MsgType_REQUEST       MsgType = 1 //请求
	MsgType_RESPONSE      MsgType = 2 //回复
	MsgType_PUSH          MsgType = 3 //服务器推送
)

// Enum value maps for MsgType.
var (
	MsgType_name = map[int32]string{
		0: "NULL_MSG_TYPE",
		1: "REQUEST",
		2: "RESPONSE",
		3: "PUSH",
	}
	MsgType_value = map[string]int32{
		"NULL_MSG_TYPE": 0,
		"REQUEST":       1,
		"RESPONSE":      2,
		"PUSH":          3,
	}
)

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}

func (x MsgType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MsgType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgs_proto_enumTypes[0].Descriptor()
}

func (MsgType) Type() protoreflect.EnumType {
	return &file_msgs_proto_enumTypes[0]
}

func (x MsgType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MsgType.Descriptor instead.
func (MsgType) EnumDescriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{0}
}

//加密类型
type EncryptType int32

const (
	EncryptType_NULL_ENCRYPT EncryptType = 0
	EncryptType_MD5          EncryptType = 1
)

// Enum value maps for EncryptType.
var (
	EncryptType_name = map[int32]string{
		0: "NULL_ENCRYPT",
		1: "MD5",
	}
	EncryptType_value = map[string]int32{
		"NULL_ENCRYPT": 0,
		"MD5":          1,
	}
)

func (x EncryptType) Enum() *EncryptType {
	p := new(EncryptType)
	*p = x
	return p
}

func (x EncryptType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EncryptType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgs_proto_enumTypes[1].Descriptor()
}

func (EncryptType) Type() protoreflect.EnumType {
	return &file_msgs_proto_enumTypes[1]
}

func (x EncryptType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EncryptType.Descriptor instead.
func (EncryptType) EnumDescriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{1}
}

//模块类型
type ModType int32

const (
	ModType_NULL_MOD ModType = 0
	ModType_BASE     ModType = 1
	//CHAT 聊天系统
	ModType_CHAT ModType = 2
	// 地图模块
	ModType_SCENE_MAP ModType = 3
)

// Enum value maps for ModType.
var (
	ModType_name = map[int32]string{
		0: "NULL_MOD",
		1: "BASE",
		2: "CHAT",
		3: "SCENE_MAP",
	}
	ModType_value = map[string]int32{
		"NULL_MOD":  0,
		"BASE":      1,
		"CHAT":      2,
		"SCENE_MAP": 3,
	}
)

func (x ModType) Enum() *ModType {
	p := new(ModType)
	*p = x
	return p
}

func (x ModType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ModType) Descriptor() protoreflect.EnumDescriptor {
	return file_msgs_proto_enumTypes[2].Descriptor()
}

func (ModType) Type() protoreflect.EnumType {
	return &file_msgs_proto_enumTypes[2]
}

func (x ModType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ModType.Descriptor instead.
func (ModType) EnumDescriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{2}
}

//code码
type Code int32

const (
	//0~999, 通用错误码
	Code_Null                Code = 0
	Code_OK                  Code = 200 // 请求已成功，请求所希望的响应头或数据体将随此响应返回。
	Code_BadRequest          Code = 400 // 请求包含语法错误。
	Code_Unauthorized        Code = 401 // 当前请求需要用户验证。
	Code_Forbidden           Code = 403 // 服务器已理解请求，但拒绝执行它。
	Code_InternalServerError Code = 500 // 服务器遇到了一个未曾预料的状况，导致了它无法完成对请求的处理。
	//>999 业务错误码
	Code_UserBan      Code = 1000 //封禁用户
	Code_MatchErr     Code = 1001 //匹配失败
	Code_NoGold       Code = 1004 //没有元宝
	Code_BetIsMax     Code = 1005 //限红
	Code_LowGold      Code = 1006 //元宝太少
	Code_ShopNotExist Code = 1009 //购买的商品不存在
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:    "Null",
		200:  "OK",
		400:  "BadRequest",
		401:  "Unauthorized",
		403:  "Forbidden",
		500:  "InternalServerError",
		1000: "UserBan",
		1001: "MatchErr",
		1004: "NoGold",
		1005: "BetIsMax",
		1006: "LowGold",
		1009: "ShopNotExist",
	}
	Code_value = map[string]int32{
		"Null":                0,
		"OK":                  200,
		"BadRequest":          400,
		"Unauthorized":        401,
		"Forbidden":           403,
		"InternalServerError": 500,
		"UserBan":             1000,
		"MatchErr":            1001,
		"NoGold":              1004,
		"BetIsMax":            1005,
		"LowGold":             1006,
		"ShopNotExist":        1009,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_msgs_proto_enumTypes[3].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_msgs_proto_enumTypes[3]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{3}
}

type MsgHead struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type     MsgType     `protobuf:"varint,1,opt,name=type,proto3,enum=msgs.MsgType" json:"type,omitempty"`           ///< 命令字（压缩加密算法占高位1字节）
	Encrypt  EncryptType `protobuf:"varint,2,opt,name=encrypt,proto3,enum=msgs.EncryptType" json:"encrypt,omitempty"` ///< 加密类型
	CheckNum uint32      `protobuf:"fixed32,3,opt,name=check_num,json=checkNum,proto3" json:"check_num,omitempty"`    ///< 校验消息的完整性,防止消息被篡改
}

func (x *MsgHead) Reset() {
	*x = MsgHead{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgHead) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgHead) ProtoMessage() {}

func (x *MsgHead) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgHead.ProtoReflect.Descriptor instead.
func (*MsgHead) Descriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{0}
}

func (x *MsgHead) GetType() MsgType {
	if x != nil {
		return x.Type
	}
	return MsgType_NULL_MSG_TYPE
}

func (x *MsgHead) GetEncrypt() EncryptType {
	if x != nil {
		return x.Encrypt
	}
	return EncryptType_NULL_ENCRYPT
}

func (x *MsgHead) GetCheckNum() uint32 {
	if x != nil {
		return x.CheckNum
	}
	return 0
}

type MsgBody struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mod     ModType `protobuf:"varint,1,opt,name=mod,proto3,enum=msgs.ModType" json:"mod,omitempty"`     ///< 消息所属模块（压缩加密算法占高位1字节）,用于消息路由
	Cmd     int32   `protobuf:"varint,2,opt,name=cmd,proto3" json:"cmd,omitempty"`                       ///< 消息命令字（压缩加密算法占高位1字节）,用于消息路由
	Data    []byte  `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`                      ///< 消息体主体,真正的业务数据内容,按照业务需要填写
	TraceId string  `protobuf:"bytes,4,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` ///< 错误跟踪使用,预留（客户端无须理会）
	Mid     uint32  `protobuf:"varint,5,opt,name=mid,proto3" json:"mid,omitempty"`                       ///< 消息序列号
	// Types that are assignable to MsgType:
	//	*MsgBody_ReqTarget
	//	*MsgBody_RspResult
	//	*MsgBody_RspPush
	MsgType isMsgBody_MsgType `protobuf_oneof:"msg_type"`
}

func (x *MsgBody) Reset() {
	*x = MsgBody{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBody) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBody) ProtoMessage() {}

func (x *MsgBody) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBody.ProtoReflect.Descriptor instead.
func (*MsgBody) Descriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{1}
}

func (x *MsgBody) GetMod() ModType {
	if x != nil {
		return x.Mod
	}
	return ModType_NULL_MOD
}

func (x *MsgBody) GetCmd() int32 {
	if x != nil {
		return x.Cmd
	}
	return 0
}

func (x *MsgBody) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *MsgBody) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *MsgBody) GetMid() uint32 {
	if x != nil {
		return x.Mid
	}
	return 0
}

func (m *MsgBody) GetMsgType() isMsgBody_MsgType {
	if m != nil {
		return m.MsgType
	}
	return nil
}

func (x *MsgBody) GetReqTarget() *MsgBody_Request {
	if x, ok := x.GetMsgType().(*MsgBody_ReqTarget); ok {
		return x.ReqTarget
	}
	return nil
}

func (x *MsgBody) GetRspResult() *MsgBody_Response {
	if x, ok := x.GetMsgType().(*MsgBody_RspResult); ok {
		return x.RspResult
	}
	return nil
}

func (x *MsgBody) GetRspPush() *MsgBody_Push {
	if x, ok := x.GetMsgType().(*MsgBody_RspPush); ok {
		return x.RspPush
	}
	return nil
}

type isMsgBody_MsgType interface {
	isMsgBody_MsgType()
}

type MsgBody_ReqTarget struct {
	ReqTarget *MsgBody_Request `protobuf:"bytes,10,opt,name=req_target,json=reqTarget,proto3,oneof"` ///< 请求目标（请求包必须填充）
}

type MsgBody_RspResult struct {
	RspResult *MsgBody_Response `protobuf:"bytes,11,opt,name=rsp_result,json=rspResult,proto3,oneof"` ///< 响应结果（响应包必须填充）
}

type MsgBody_RspPush struct {
	RspPush *MsgBody_Push `protobuf:"bytes,12,opt,name=rsp_push,json=rspPush,proto3,oneof"` ///< 响应结果（响应包必须填充）
}

func (*MsgBody_ReqTarget) isMsgBody_MsgType() {}

func (*MsgBody_RspResult) isMsgBody_MsgType() {}

func (*MsgBody_RspPush) isMsgBody_MsgType() {}

type MsgBody_Request struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	V uint32 `protobuf:"varint,1,opt,name=v,proto3" json:"v,omitempty"` ///< 版本号 ,用于消息路由,客户端填写版本号,服务器根据版本号做不同的处理,客户端负责填充
}

func (x *MsgBody_Request) Reset() {
	*x = MsgBody_Request{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBody_Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBody_Request) ProtoMessage() {}

func (x *MsgBody_Request) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBody_Request.ProtoReflect.Descriptor instead.
func (*MsgBody_Request) Descriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{1, 0}
}

func (x *MsgBody_Request) GetV() uint32 {
	if x != nil {
		return x.V
	}
	return 0
}

type MsgBody_Response struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code Code   `protobuf:"varint,1,opt,name=code,proto3,enum=msgs.Code" json:"code,omitempty"` ///< 成功或者 错误码
	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`                 ///< 提示信息
}

func (x *MsgBody_Response) Reset() {
	*x = MsgBody_Response{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBody_Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBody_Response) ProtoMessage() {}

func (x *MsgBody_Response) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBody_Response.ProtoReflect.Descriptor instead.
func (*MsgBody_Response) Descriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{1, 1}
}

func (x *MsgBody_Response) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Null
}

func (x *MsgBody_Response) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type MsgBody_Push struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Info string `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"` ///< 提示信息
}

func (x *MsgBody_Push) Reset() {
	*x = MsgBody_Push{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msgs_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MsgBody_Push) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MsgBody_Push) ProtoMessage() {}

func (x *MsgBody_Push) ProtoReflect() protoreflect.Message {
	mi := &file_msgs_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MsgBody_Push.ProtoReflect.Descriptor instead.
func (*MsgBody_Push) Descriptor() ([]byte, []int) {
	return file_msgs_proto_rawDescGZIP(), []int{1, 2}
}

func (x *MsgBody_Push) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

var File_msgs_proto protoreflect.FileDescriptor

var file_msgs_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x6d, 0x73,
	0x67, 0x73, 0x22, 0x78, 0x0a, 0x07, 0x4d, 0x73, 0x67, 0x48, 0x65, 0x61, 0x64, 0x12, 0x22, 0x0a,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x73,
	0x67, 0x73, 0x2e, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x12, 0x2c, 0x0a, 0x07, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70,
	0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x07, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x07, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x4e, 0x75, 0x6d, 0x22, 0xa1, 0x03, 0x0a,
	0x07, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x12, 0x20, 0x0a, 0x03, 0x6d, 0x6f, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0e, 0x2e, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x6d, 0x6f, 0x64,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x52, 0x03, 0x6d, 0x6f, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x63, 0x6d,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x63, 0x6d, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x63, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x72, 0x61, 0x63, 0x65, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x69, 0x64, 0x12, 0x36, 0x0a,
	0x0a, 0x72, 0x65, 0x71, 0x5f, 0x74, 0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x15, 0x2e, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x09, 0x72, 0x65, 0x71, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x12, 0x37, 0x0a, 0x0a, 0x72, 0x73, 0x70, 0x5f, 0x72, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x73, 0x67, 0x73,
	0x2e, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x48, 0x00, 0x52, 0x09, 0x72, 0x73, 0x70, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x2f,
	0x0a, 0x08, 0x72, 0x73, 0x70, 0x5f, 0x70, 0x75, 0x73, 0x68, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x4d, 0x73, 0x67, 0x42, 0x6f, 0x64, 0x79, 0x2e,
	0x50, 0x75, 0x73, 0x68, 0x48, 0x00, 0x52, 0x07, 0x72, 0x73, 0x70, 0x50, 0x75, 0x73, 0x68, 0x1a,
	0x17, 0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0c, 0x0a, 0x01, 0x76, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x01, 0x76, 0x1a, 0x3e, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x6d, 0x73, 0x67, 0x73, 0x2e, 0x63, 0x6f, 0x64, 0x65, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x1a, 0x1a, 0x0a, 0x04, 0x50, 0x75, 0x73, 0x68,
	0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x69, 0x6e, 0x66, 0x6f, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x2a, 0x42, 0x0a, 0x08, 0x6d, 0x73, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d,
	0x4e, 0x55, 0x4c, 0x4c, 0x5f, 0x4d, 0x53, 0x47, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x00, 0x12,
	0x0b, 0x0a, 0x07, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08,
	0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x50, 0x55,
	0x53, 0x48, 0x10, 0x03, 0x2a, 0x29, 0x0a, 0x0c, 0x65, 0x6e, 0x63, 0x72, 0x79, 0x70, 0x74, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x0c, 0x4e, 0x55, 0x4c, 0x4c, 0x5f, 0x45, 0x4e, 0x43,
	0x52, 0x59, 0x50, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x4d, 0x44, 0x35, 0x10, 0x01, 0x2a,
	0x3b, 0x0a, 0x08, 0x6d, 0x6f, 0x64, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x4e,
	0x55, 0x4c, 0x4c, 0x5f, 0x4d, 0x4f, 0x44, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x42, 0x41, 0x53,
	0x45, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x43, 0x48, 0x41, 0x54, 0x10, 0x02, 0x12, 0x0d, 0x0a,
	0x09, 0x53, 0x43, 0x45, 0x4e, 0x45, 0x5f, 0x4d, 0x41, 0x50, 0x10, 0x03, 0x2a, 0xc1, 0x01, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x4e, 0x75, 0x6c, 0x6c, 0x10, 0x00, 0x12,
	0x07, 0x0a, 0x02, 0x4f, 0x4b, 0x10, 0xc8, 0x01, 0x12, 0x0f, 0x0a, 0x0a, 0x42, 0x61, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x10, 0x90, 0x03, 0x12, 0x11, 0x0a, 0x0c, 0x55, 0x6e, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x65, 0x64, 0x10, 0x91, 0x03, 0x12, 0x0e, 0x0a, 0x09,
	0x46, 0x6f, 0x72, 0x62, 0x69, 0x64, 0x64, 0x65, 0x6e, 0x10, 0x93, 0x03, 0x12, 0x18, 0x0a, 0x13,
	0x49, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x10, 0xf4, 0x03, 0x12, 0x0c, 0x0a, 0x07, 0x55, 0x73, 0x65, 0x72, 0x42, 0x61,
	0x6e, 0x10, 0xe8, 0x07, 0x12, 0x0d, 0x0a, 0x08, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x45, 0x72, 0x72,
	0x10, 0xe9, 0x07, 0x12, 0x0b, 0x0a, 0x06, 0x4e, 0x6f, 0x47, 0x6f, 0x6c, 0x64, 0x10, 0xec, 0x07,
	0x12, 0x0d, 0x0a, 0x08, 0x42, 0x65, 0x74, 0x49, 0x73, 0x4d, 0x61, 0x78, 0x10, 0xed, 0x07, 0x12,
	0x0c, 0x0a, 0x07, 0x4c, 0x6f, 0x77, 0x47, 0x6f, 0x6c, 0x64, 0x10, 0xee, 0x07, 0x12, 0x11, 0x0a,
	0x0c, 0x53, 0x68, 0x6f, 0x70, 0x4e, 0x6f, 0x74, 0x45, 0x78, 0x69, 0x73, 0x74, 0x10, 0xf1, 0x07,
	0x42, 0x0d, 0x5a, 0x0b, 0x2e, 0x2f, 0x6d, 0x73, 0x67, 0x73, 0x3b, 0x6d, 0x73, 0x67, 0x73, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msgs_proto_rawDescOnce sync.Once
	file_msgs_proto_rawDescData = file_msgs_proto_rawDesc
)

func file_msgs_proto_rawDescGZIP() []byte {
	file_msgs_proto_rawDescOnce.Do(func() {
		file_msgs_proto_rawDescData = protoimpl.X.CompressGZIP(file_msgs_proto_rawDescData)
	})
	return file_msgs_proto_rawDescData
}

var file_msgs_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_msgs_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_msgs_proto_goTypes = []interface{}{
	(MsgType)(0),             // 0: msgs.msg_type
	(EncryptType)(0),         // 1: msgs.encrypt_type
	(ModType)(0),             // 2: msgs.mod_type
	(Code)(0),                // 3: msgs.code
	(*MsgHead)(nil),          // 4: msgs.MsgHead
	(*MsgBody)(nil),          // 5: msgs.MsgBody
	(*MsgBody_Request)(nil),  // 6: msgs.MsgBody.Request
	(*MsgBody_Response)(nil), // 7: msgs.MsgBody.Response
	(*MsgBody_Push)(nil),     // 8: msgs.MsgBody.Push
}
var file_msgs_proto_depIdxs = []int32{
	0, // 0: msgs.MsgHead.type:type_name -> msgs.msg_type
	1, // 1: msgs.MsgHead.encrypt:type_name -> msgs.encrypt_type
	2, // 2: msgs.MsgBody.mod:type_name -> msgs.mod_type
	6, // 3: msgs.MsgBody.req_target:type_name -> msgs.MsgBody.Request
	7, // 4: msgs.MsgBody.rsp_result:type_name -> msgs.MsgBody.Response
	8, // 5: msgs.MsgBody.rsp_push:type_name -> msgs.MsgBody.Push
	3, // 6: msgs.MsgBody.Response.code:type_name -> msgs.code
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_msgs_proto_init() }
func file_msgs_proto_init() {
	if File_msgs_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msgs_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgHead); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgs_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBody); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgs_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBody_Request); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgs_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBody_Response); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msgs_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MsgBody_Push); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_msgs_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*MsgBody_ReqTarget)(nil),
		(*MsgBody_RspResult)(nil),
		(*MsgBody_RspPush)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msgs_proto_rawDesc,
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msgs_proto_goTypes,
		DependencyIndexes: file_msgs_proto_depIdxs,
		EnumInfos:         file_msgs_proto_enumTypes,
		MessageInfos:      file_msgs_proto_msgTypes,
	}.Build()
	File_msgs_proto = out.File
	file_msgs_proto_rawDesc = nil
	file_msgs_proto_goTypes = nil
	file_msgs_proto_depIdxs = nil
}
